# Generated by Django 4.0.5 on 2022-06-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesentities',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='dealer_id',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='featured_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='is_active',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='is_featured',
            field=models.IntegerField(default=0, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='is_pending',
            field=models.IntegerField(default=1, max_length=11),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='meta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='related_to',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='related_to1',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='related_to2',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='related_to3',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='related_to4',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='search_keywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='thirdparty_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='type',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='user_id',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoriesentities',
            name='vendor_id',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='categoriesentities',
            name='id',
            field=models.PositiveBigIntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
