# Generated by Django 4.0.5 on 2022-06-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoriesentities_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitiesRelation',
            fields=[
                ('id', models.BigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='entities_relation',
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='dealer_id',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='featured_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='is_active',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='is_featured',
            field=models.IntegerField(default=0, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='is_pending',
            field=models.IntegerField(default=1, max_length=11),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='meta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='related_to',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='related_to1',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='related_to2',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='related_to3',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='related_to4',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='search_keywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='thirdparty_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='type',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='user_id',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoryentities',
            name='vendor_id',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='dealer_id',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='featured_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='is_active',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='entities',
            name='is_featured',
            field=models.IntegerField(default=0, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='is_pending',
            field=models.IntegerField(default=1, max_length=11),
        ),
        migrations.AddField(
            model_name='entities',
            name='meta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='related_to',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='related_to1',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='related_to2',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='related_to3',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='related_to4',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='search_keywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='thirdparty_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='type',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='entities',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='user_id',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='vendor_id',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='categoryentities',
            name='id',
            field=models.PositiveBigIntegerField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entities',
            name='id',
            field=models.PositiveBigIntegerField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='entitiesrelation',
            name='entity_id_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entities'),
        ),
    ]
