# Generated by Django 4.0.5 on 2022-06-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_entitiesrelation_delete_entities_relation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitiesrelation',
            old_name='entity_id_1',
            new_name='entity_id',
        ),
    ]
