# Generated by Django 4.0.5 on 2022-06-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_entity_id_1_entitiesrelation_entity_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='report_leads',
            new_name='ReportLeads',
        ),
        migrations.RenameModel(
            old_name='report_top_queries',
            new_name='ReportsTopListing',
        ),
        migrations.RenameModel(
            old_name='reports_top_listing',
            new_name='ReportTopCountries',
        ),
        migrations.RenameModel(
            old_name='report_top_customers',
            new_name='ReportTopCustomers',
        ),
        migrations.RenameModel(
            old_name='report_top_countries',
            new_name='ReportTopQueries',
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='dealer_id',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='featured_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='is_active',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='is_featured',
            field=models.IntegerField(default=0, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='is_pending',
            field=models.IntegerField(default=1, max_length=11),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='meta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='related_to',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='related_to1',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='related_to2',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='related_to3',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='related_to4',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='search_keywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='thirdparty_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='type',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='user_id',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentities',
            name='vendor_id',
            field=models.PositiveBigIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='migrations',
            name='batch',
            field=models.IntegerField(default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='migrations',
            name='migration',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='card_brand',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='card_last_four',
            field=models.CharField(default=None, max_length=4),
        ),
        migrations.AddField(
            model_name='users',
            name='company_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='email_verified_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='users',
            name='from_email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='from_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='is_admin',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='users',
            name='is_dealer',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='package',
            field=models.CharField(default='Free', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='remember_token',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='stripe_id',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='trial_ends_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='inventoryentities',
            name='id',
            field=models.PositiveBigIntegerField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='migrations',
            name='id',
            field=models.PositiveBigIntegerField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.PositiveBigIntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
