# Generated by Django 4.0.5 on 2022-06-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_modelsentities_permissions_roles_reports_clicks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesentities',
            name='dealer_id',
            field=models.PositiveIntegerField(max_length=100, null=True),
        ),
    ]
