# Generated by Django 4.0.5 on 2022-06-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.PositiveBigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('dealer_id', models.PositiveBigIntegerField(max_length=20)),
                ('month', models.DateField()),
                ('impression', models.PositiveBigIntegerField(default=0, max_length=20)),
                ('clicks', models.PositiveBigIntegerField(default=0, max_length=20)),
                ('lead_count', models.PositiveBigIntegerField(default=0, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventoryentities',
            name='dealer_id',
        ),
        migrations.RemoveField(
            model_name='modelsentities',
            name='dealer_id',
        ),
    ]
